### ISSUE TITLE
Battletoads and Double Dragon - The Ultimate Team (U) hangs

### ISSUE THREAD

**Issue by eugene-s-nesdev** [andrew-hoffman/halfnes#15]
Battletoads and Double Dragon - The Ultimate Team (U).nes 
***
CRC32: 53B02F3D
MD5: 35933222CF8658F7C6679FC7DE630AAA
SHA-1: 61832D0F955CFF169FF059BD557BE4F522B15B7C
***
hangs on pseudo-3D levels (1,6,7) when RAW 7-bit PCM samples play (beat enemy or pause drum)
and lifebar also shakes on level 2 for the same reasons.
![halfnes](https://cloud.githubusercontent.com/assets/13199529/8960112/1f481734-3617-11e5-848f-05813d47fab2.png)

**Comment by andrew-hoffman** [comment]
Broken since version 057.

**Comment by andrew-hoffman** [comment]
It's getting stuck waiting for a sprite 0 hit that never happens. Not sure why

**Comment by andrew-hoffman** [comment]
The Battletoads Wookie Hole freezes after some time in the same way so it's probably a timing issue

**Comment by andrew-hoffman** [comment]
This really needs a cycle accurate CPU core. Here's an illustration of the problem. 
We write the x scroll here on dot 252, 5 PPU clocks too early (or about  1 2/3 cpu cycles too early)
But notice that we do all of an instruction on the first PPU cycle of the instruction
and STA $2001 should take 4 CPU clocks or 12 ppu clocks
    PPU: 252 253 254 255 256 257 258 259 260 261 262 263 264
    CPU:  |  Read op  | read $01  | read $20  | store Acc |
    Scroll reset happens      *here when PPU is on
    and we should turn the PPU on               *about here (depending on power on clock alignment)
          * but actually we turn it on here because not cycle accurate
