### ISSUE TITLE
Check functionality on Mac OS El Capitan

### ISSUE THREAD

**Issue by andrew-hoffman** [andrew-hoffman/halfnes#17]
someone commented that the .app file I've built doesn't work any more (it was a Japanese OS) but I don't have a Mac that can even run Yosemite. Need to check this in the graphic design comp. lab or something.

**Comment by Ivoah** [comment]
The .app file doesn't work on OS X El Capitan, it says it's a PowerPC application.

**Comment by andrew-hoffman** [comment]
That's what I thought. I should probably just stop providing it because the .jar works just as well except if you don't have Java installed and then it can't give you the helpful little message.

**Comment by andrew-hoffman** [comment]
With the new build system I'm only doing an .exe and .jar so this is resolved.
