### ISSUE TITLE
Usage as library

### ISSUE THREAD

**Issue by klaushauschild1984** [andrew-hoffman/halfnes#19]
I want to use halfnes as library.
Currently it is a stand-alone app only. What I need is embedding the emulation as library, remote control the input and grap all the output data (screen, sound, etc). Of course the hole emulation should run headless.

If you want this but not familiar with this kind of task I can contribute.

**Comment by magneticflux-** [comment]
@klaushauschild1984 I started a fork a few months ago that adds the ability to toggle whether the window is displayed. It's pretty hacked together and old, but it works well enough for what I needed. I used it to rapidly simulate multiple NESs in parallel for a neural network experiment.

**Comment by klaushauschild1984** [comment]
Is this fork in github?

**Comment by magneticflux-** [comment]
@klaushauschild1984 Yep, right [here](https://github.com/magneticflux-/halfnes-headless).
