### ISSUE TITLE
Unitests NEEDED

### ISSUE THREAD

**Issue by klaushauschild1984** [andrew-hoffman/halfnes#20]
There are no unit tests or something that ensures the correct functionality.

Some unit test would be nice.
Another aproach are integration tests with the various test-roms out there.

**Comment by andrew-hoffman** [comment]
The current layout of the code makes mocking things for unit tests kind of difficult, but you're right that it should at least run some test ROMs and capture the output. Lots of blargg's tests log to 0x8000 in memory so those are easy, but subtle visual bugs or hangs in games may require running the emulator with a movie file for several minutes and capturing each frame. 

Need to add a headless build target back, that's been missing for quite a while.

**Comment by klaushauschild1984** [comment]
This is the right spirit. Let's refactor halfnes that unit tests are possible. But first I would start with some test roms for automated cpu tests, for instance "nestest.nes".
Then see how far we could get.
For this tasks I would like to provide another pull request in the next days.

**Comment by klaushauschild1984** [comment]
http://wiki.nesdev.com/w/index.php/Emulator_tests

**Comment by andrew-hoffman** [comment]
I am aware of that archive of tests. Not all of them pass currently for various reasons.

**Comment by klaushauschild1984** [comment]
There should also be a continous integration like TraivsCI (https://travis-ci.org/).
For my fork I have already configured it. With the last merge you get the configuration file in the repo (.travis.yml). Your last task is to create an account at Travis with you GitHub account and let halfNES build continously.

**Comment by klaushauschild1984** [comment]
After merge, this can be closed.
