### ISSUE TITLE
Will not build

### ISSUE THREAD

**Issue by karlstrings** [andrew-hoffman/halfnes#3]
There is an issue with the current revision, it does not build or run without modification.

There are unstated deps taken on libs, these need to be found and added. There is also broken code around controller detection.

**Comment by klaushauschild1984** [comment]
What about to mavenize the whole project?
Maybe also remove the need of the Happy Java Lib (because there is no maven artifact for it) and replace the usages with some other library.

**Comment by klaushauschild1984** [comment]
To perform the described tasks was easy. Now the hard stuff and you must help please:

Which steps has to be performed to create the ready-to-execute assemblies?

**Comment by andrew-hoffman** [comment]
The jar file, library JARs and native DLLs are all packed together using JarSplice, a jar of which is in the Github repo and the script I use with that is in package.bat. It's not being actively developed any more and is outdated but OneJar never really did what I needed it to do and it feels excessive to use an installer.

**Comment by klaushauschild1984** [comment]
Ok, than I will mimic this stuff also with Maven and prepare a pull request.

During this I would also clean up the project from NetBeans stuff and libraries that not any more used or obtained by Maven.
The goal of this is a clean repo without IDE specific stuff, just the pure sources and build scripts.
There are any doubts?

**Comment by klaushauschild1984** [comment]
Have a look at my fork of halfnes (https://github.com/klaushauschild1984/halfnes) for the first WiP for this task.
The conversion to a legit maven project is almost done. Currently the packaging is not working. But I will fix this soon.

**Comment by andrew-hoffman** [comment]
anyone should be able to build this now.
