### ISSUE TITLE
Native files never deleted on Windows 7

### ISSUE THREAD

**Issue by andrew-hoffman** [andrew-hoffman/halfnes#37]
I just realized I have like 200 copies of jinput-dx8.dll in my Temp folder, all in folders named things like halfNES-natives2281448322177416404. When the natives are created the files and the folder are set to be deleted on exit by calling (file handle).deleteOnExit(); but it doesn't seem to happen. It's not that big of a deal since each set of natives is only 64k but that could still add up over time.

I tried redesigning the Quit methods to eliminate the call to System.exit(0) and did make some things more consistent in the process, like I didn't realize that window position was only saved when you used the Quit command from the menu, but the temp files are still not deleted when I don't use System.exit at all.

Doesn't matter whether I run it inside or outside the IDE.

Need to check if this works on other platforms.

**Comment by andrew-hoffman** [comment]
OK it's deleting some of the natives but not all, the ones that aren't deleted are probably the ones actually in use.The native files might still be open somewhere in the JVM until the very instant it is terminated, and Windows won't let you delete an open file.

Is there a way I can close and unload the natives before quitting?

**Comment by klaushauschild1984** [comment]
Ufff
You have to trick around with custom classloader loading and unloding the native. When the classloader is garbage collected than the native will be unloaded and can be deleted.

See here https://web.archive.org/web/20140704120535/http://www.codethesis.com/blog/unload-java-jni-dll

**Comment by andrew-hoffman** [comment]
Or I can just make the name of the temp folder consistent for each version so I won't get 200 copies hanging around. Still not ideal but better than programs that put a MSI installer in the temp folder and then still expect it to be there when I try to uninstall or update it months later. Thanks VirtualBox.

**Comment by klaushauschild1984** [comment]
Thats an option too.

**Comment by andrew-hoffman** [comment]
To make a custom classloader work it looks like I'm really going to have to rip into the JInput library.

**Comment by andrew-hoffman** [comment]
Made the name of the temp folder stay consistent for each version, and also avoided throwing an exception if the natives can't be created (because another copy of the emulator is already running and has created and locked the files). 

On Windows I guess I don't have to worry about 1 instance deleting the natives out from under another one, since anything that's used is locked and not deleted anyway.

On Linux maybe I should still use a random name for the temp folder to avoid this? need to check.
