### ISSUE TITLE
Disable audio, bug

### ISSUE THREAD

**Issue by tangvfr** [andrew-hoffman/halfnes#45]
When to disable audio, the timing of emulator if too fast. Speed of frame don't  60 or 50 HZ when to disable audio.

**Comment by andrew-hoffman** [comment]
Emulator itiming is controlled by the audio buffer because I didn't have
any good options for waiting for VSync on the computer.

**Comment by tangvfr** [comment]
Okay man, thank for the information

Le sam. 18 juin 2022 à 23:02, Andrew Hoffman ***@***.***> a
écrit :

> Emulator itiming is controlled by the audio buffer because I didn't have
> any good options for waiting for VSync on the computer.
>
