### ISSUE TITLE
add PAL and Dendy mode

### ISSUE THREAD

**Issue by eugene-s-nesdev** [andrew-hoffman/halfnes#7]
Hi, Andrew.

Can you add PAL and Dendy (NTSC/PAL Hybrid) modes to halfnes please?

"Dendy-mode" is basically NTSC mode, but with a longer pre-vblank time,
and running at 50FPS instead of 60FPS. 
This mode allow to run most of NTSC games (Jap, USA) on 50Hz without glitches, with correct DPCM sound pitch also.

1:
Here is CORRECT and enough information about timings:
http://wiki.nesdev.com/w/index.php/Clock_rate

differences between NES NTSC/FC, NES PAL, and Dendy:
http://wiki.breaknes.com/_media/wiki:2652378.png?cache=
http://savepic.su/2652378.htm

NMI info:
http://wiki.nesdev.com/w/index.php/NES_2.0#TV_system
http://forums.nesdev.com/viewtopic.php?p=81513#p81513
http://forums.nesdev.com/viewtopic.php?p=147360#p147360

pAPU tables (Noise, DPCМ) are same as NTSC:
http://forums.nesdev.com/viewtopic.php?p=91333#p91333

FCEUX (since svn3111), Nestopia, Nintendulator, puNES, BizHawk, MyNES
and Retrocopy emulators already has support "dendy-mode".
Nintendulator names it as "Hybrid-mode".

2:
Dendy timings have specific behavior, causing some in-game glitches, so here is info "how-to-test dendy-mode":

First ROM is "Battletoads and Double Dragon (U)"
It must look like:
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Battletoads%20Double%20Dragon.gif

Second ROM is "Choujin Sentai - Jetman (J)"
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Choujin%20Sentai%20Jetman.gif

Third ROM is "Journey to Silius (U)" (it's DMC test)
Pitch (4 channels + DMC) must be sound like: http://hwm.us.to/famimusic/Forum/Journey_to_Silius_Title.mp3

lastest nintendulator WIP with dendy (aka hybrid) mode:
http://www.qmtpro.com/~nes/nintendulator/nintendulator_bin_unicode.zip

P.S:
"Dendy-mode" is only euphonic name. A thousands of "NTSC/PAL hybrid" famiclones work on this timings.
They have different labels/names in CIS countries ("Dendy", "Lifa", "Kenga", "Subor", etc),
Eastern Europe (i know "Pegasus" in Poland) and Asian region ("MicroGenius" in Taiwan).

*******************************************************
Thank you for support.
Eugene Sergunov (nesdev.com)
*******************************************************

**Comment by andrew-hoffman** [comment]
I can do some work on this but I'm not in a PAL country and so I won't have any real PAL hardware (of either type) to compare to. Also I intend to leave NTSC as the default region, because most PAL ROMs currently in distribution do not have any of the 3 possibilities for region bits set in the header and I do not want to maintain a ROM database.

This is also a good excuse to at least attempt to read iNES 2 style headers, even if I don't support the Playchoice 10 or any of the newer multicart/pirate mappers that have numbers over 255

**Comment by eugene-s-nesdev** [comment]
Anyway, you need to add force region (NTSC/PAL/Dendy) selector to GUI.
Dendy-mode was designed only for run actual NTSC-games at 50FPS
So, none of exclusive software/games was written special for dendy-mode
and region detection (based on NstDatabase.xml or similar) can't detect Dendy.

**Comment by eugene-s-nesdev** [comment]
Вторник,  7 июля 2015, 18:02 -07:00 от Andrew Hoffman <notifications@github.com>:
>I can do some work on this but I'm not in a PAL country and so I won't have any real PAL hardware (of either type) to compare to. Also I intend to leave NTSC as the default region, because most PAL ROMs currently in distribution do not have any of the 3 possibilities for region bits set in the header and I do not want to maintain a ROM database.
>This is also a good excuse to at least attempt to read iNES 2 style headers, even if I don't support the Playchoice 10 or any of the newer multicart/pirate mappers that have numbers over 255
>—
>Reply to this email directly or  view it on GitHub .

Anyway, you need to add force region (NTSC/PAL/Dendy) selector to GUI.
Dendy-mode was designed only for run actual NTSC-games at 50FPS
So, none of exclusive software/games was written special for dendy-mode
and region detection (based on NstDatabase.xml or similar) can't detect Dendy.

**Comment by andrew-hoffman** [comment]
Well I've done most of this now. Still some problems if the region is changed while a game is running. If you can build it let me know how it is; if you can't build it I'll send you a zip file.

**Comment by andrew-hoffman** [comment]
For the authentic Dendy experience (according to Kinaman) I probably also need to add turbo A and B buttons and the snowy black-and-white picture you get from an old SECAM TV. (And maybe ducktales)
![b116e9385](https://cloud.githubusercontent.com/assets/5531580/8611930/7ee4b11a-267d-11e5-90a8-99db626cea13.jpg)
 But I probably won't do those yet.

**Comment by eugene-s-nesdev** [comment]
Sent me zip file please and I'll try it.
--
Отправлено из Mail.Ru для Android пятница, 10 июля 2015г., 05:20 +0300 от Andrew Hoffman < notifications@github.com> :

**Comment by eugene-s-nesdev** [comment]
>Четверг,  9 июля 2015, 21:00 -07:00 от Andrew Hoffman <notifications@github.com>:
>
>For the authentic Dendy experience (according to Kinaman) I probably also need to add turbo A and B buttons and the snowy black-and-white picture you get from an old SECAM TV. (And maybe ducktales)

Oh, no need to emulate pirate DuckTales or black-and-white old CRT.
Turbo-buttons support will be nice ( turboA="S", turboB="A" on default keyb input ). 
The standard Dendy turbo-controller toggle every frame, 
like this:  http://savepic.su/2525036.htm

I have a question about halfnes 0.58 also: when i set 4x scale window or fullscreen
emulator higly slowdown, 23FPS. 
I use Core i7-2600K/HD Graphics300/Win7x64 and lastest java

**Comment by eugene-s-nesdev** [comment]
http://savepic.ru/7546066.png

**Comment by andrew-hoffman** [comment]
Turn smooth scaling off and things will run faster. The Swing UI in Java is really slow at doing binary interpolation now, it's gotten worse over time instead of better, I should move everything to SDL or LWJGL but there are reasons that I haven't. 

Anyway, I've uploaded a preview release of HalfNES 059 if you want to try it, which should run Dendy stuff OK as long as you don't change regions while a game is running.

**Comment by eugene-s-nesdev** [comment]
Hi, PAL and Dendy timings work good. I've tested Battletoads&D.D 
and some other timing-specific stuff. 
But here is strange issue: Gamespeed and music tempo is too slow in PAL and Dendy modes, like 35FPS, despite emulator shows me 50FPS. Maybe problem with syncro.

**Comment by eugene-s-nesdev** [comment]
Also, tepples timing/overclock demo ROM, work good and correct too:
https://user-images.githubusercontent.com/13199529/98018347-7cae3100-1e11-11eb-9571-927bab3019d7.png

**Comment by andrew-hoffman** [comment]
Fixed the gamespeed. (I was still outputting a frame of audio every 262 lines.)

**Comment by andrew-hoffman** [comment]
I think that's everything except the occasional deadlock when changing regions (and that has to be a threading bug, I know it)

**Comment by eugene-s-nesdev** [comment]
Thank you. I'll wait updated 059beta.
Also, i can run any test roms on Dendy via flashcartridge, if you need it.
http://forums.nesdev.com/viewtopic.php?f=22&t=12499#p146813

**Comment by eugene-s-nesdev** [comment]
Yes, updated beta-2 work correct.
